### ISSUE TITLE
How to add Sencha ExtJS SDK?.

### ISSUE THREAD

**Issue by asprakash** [walkingtree/arbela#2]
Hi Ajit,
I downloaded the Sencha SDK 5.1.1 from here https://github.com/tremez/extjs-gpl But I have no idea about where to add this sdk in arbela source. Can you please clarify. Some kind of elaborated document should be very useful. 

TIA,
Prakash

**Comment by ajit-kumar-azad** [comment]
Please refer to Step 2 of https://github.com/walkingtree/arbela/#how-to-test-drive

**Comment by asprakash** [comment]
Hi Ajit,
Thanks for your prompt reply. You mean, I want to copy all these files https://github.com/tremez/extjs-gpl into "ext" folder of arbela source?.

**Comment by ajit-kumar-azad** [comment]
Yepp
